CinemaBooking/Controllers/ActorController.cs
namespace CinemaBooking.Controllers
{
    public class ActorController : Controller
    {


        private readonly IActorRepository _actorRepository;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ActorController(IActorRepository actorRepository, IWebHostEnvironment webHostEnvironment)
        {
            _actorRepository = actorRepository;
            _webHostEnvironment = webHostEnvironment;
        }
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var actors = await _actorRepository.GetAllAsync();
            return View(actors);
        }
        [Authorize]

        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("FullName", "Bio", "ImageFile")] Actor actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);
            }
            string wwwRootPath = _webHostEnvironment.WebRootPath;
            string fileName = Path.GetFileNameWithoutExtension(actor.ImageFile.FileName);
            string extension = Path.GetExtension(actor.ImageFile.FileName);
            actor.ImagePath = fileName = fileName + DateTime.Now.ToString("yymmssff") + extension;
            string path = Path.Combine(wwwRootPath + "/Images/", fileName);
            using (var fileStream = new FileStream(path, FileMode.Create))
            {
                await actor.ImageFile.CopyToAsync(fileStream);
            }


            await _actorRepository.AddAsync(actor);


            return RedirectToAction("Index");

        }


        [Authorize]
        public async Task<IActionResult> Detail(int id)
        {
            var result = await _actorRepository.GetByIdAsync(id);
            if (result == null) return View("NotFound");
            return View(result);
        }
        [Authorize]

        public async Task<IActionResult> Edit(int id)
        {
            var result = await _actorRepository.GetByIdAsync(id);
            if (result == null) return View("NotFound");
            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("ID", "FullName", "Bio", "ImageFile")] Actor actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);
            }
            string wwwRootPath = _webHostEnvironment.WebRootPath;
            string fileName = Path.GetFileNameWithoutExtension(actor.ImageFile.FileName);
            string extension = Path.GetExtension(actor.ImageFile.FileName);
            actor.ImagePath = fileName = fileName + DateTime.Now.ToString("yymmssff") + extension;
            string path = Path.Combine(wwwRootPath + "/Images/", fileName);
            using (var fileStream = new FileStream(path, FileMode.Create))
            {
                await actor.ImageFile.CopyToAsync(fileStream);
            }

            await _actorRepository.EditAsync(id, actor);


            return RedirectToAction(nameof(Index));

        }
        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            var result = await _actorRepository.GetByIdAsync(id);
            if (result == null) return View("NotFound");
            return View(result);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmation(int id)
        {
            var result = await _actorRepository.GetByIdAsync(id);
            if (result == null) return View("NotFound");



            await _actorRepository.DeleteAsync(id);


            return RedirectToAction(nameof(Index));

        }

    }
}

CinemaBooking/Controllers/CinemaController.cs
namespace CinemaBooking.Controllers
{
    public class CinemaController : Controller
    {
        private readonly ICinemaRepository _cinemaRepository;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public CinemaController(ICinemaRepository cinemaRepository, IWebHostEnvironment webHostEnvironment)
        {
            _cinemaRepository = cinemaRepository;
            _webHostEnvironment = webHostEnvironment;
        }
        [Authorize]

        public async Task<IActionResult> Index()
        {
            var cinemas= await _cinemaRepository.GetAllAsync();
            return View(cinemas);
        }
        [Authorize]
        public async Task<IActionResult> Detail(int id)
        {
            var cinema = await _cinemaRepository.GetByIdAsync(id);
            return View(cinema);
        }
        [Authorize]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Name", "Descripition", "ImageFile")] Cinema cinema)
        {
            if (!ModelState.IsValid)
            {
                return View(cinema);
            }
            string wwwRootPath = _webHostEnvironment.WebRootPath;
            string fileName = Path.GetFileNameWithoutExtension(cinema.ImageFile.FileName);
            string extension = Path.GetExtension(cinema.ImageFile.FileName);
            cinema.Logo = fileName = fileName + DateTime.Now.ToString("yymmssff") + extension;
            string path = Path.Combine(wwwRootPath + "/Images/", fileName);
            using (var fileStream = new FileStream(path, FileMode.Create))
            {
                await cinema.ImageFile.CopyToAsync(fileStream);
            }


            await _cinemaRepository.AddAsync(cinema);


            return RedirectToAction("Index");

        }
        [Authorize]
        public async Task<IActionResult> Edit(int id)
        {
            var cinema = await _cinemaRepository.GetByIdAsync(id);
            return View(cinema);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id,[Bind("ID", "Name", "Descripition", "Logo")] Cinema cinema)
        {
            if (!ModelState.IsValid)
            {
                return View(cinema);
            }



            await _cinemaRepository.EditAsync(id,cinema);


            return RedirectToAction("Index");

        }
        [Authorize]

        public async Task<IActionResult> Delete(int id)
        {
            var result = await _cinemaRepository.GetByIdAsync(id);
            if (result == null) return View("NotFound");
            return View(result);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmation(int id)
        {
            var result = await _cinemaRepository.GetByIdAsync(id);
            if (result == null) return View("NotFound");



            await _cinemaRepository.DeleteAsync(id);


            return RedirectToAction(nameof(Index));

        }

    }
}

CinemaBooking/Controllers/MovieController.cs
using CinemaBooking.Data.ViewModels;

namespace CinemaBooking.Controllers
{
    public class MovieController : Controller
    {
        private readonly IMovieRepository _movieRepository;
        private readonly ICartItemRepository _cartItemRepository;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly ApplicationDbContext _dbContext;
        public MovieController(IMovieRepository movieRepository, ICartItemRepository cartItemRepository, IWebHostEnvironment webHostEnvironment, ApplicationDbContext dbContext)
        {
            _movieRepository = movieRepository;
            _cartItemRepository = cartItemRepository;
            _webHostEnvironment = webHostEnvironment;
            _dbContext = dbContext;
        }
        public async Task<IActionResult> Index(string stringSearch)
        {
            IEnumerable<Movie>? movies = await _movieRepository.GetAllAsync();
            ViewData["CurrentFilter"] = stringSearch;
            if (!string.IsNullOrEmpty(stringSearch))
            {
                movies = movies.Where(m => m.Name.IndexOf(stringSearch, StringComparison.OrdinalIgnoreCase) >= 0).ToList();
            }
            return View(movies);

        }

        public async Task<IActionResult> Details(int id)
        {
            var movie = await _movieRepository.GetByIdAsync(id);
            return View(movie);
        }
        [HttpPost]
        public async Task<ActionResult> Delete(int movieId)
        {
            var isMovieInCart = await _cartItemRepository.IsMovieInCart(movieId);
            var movies = await _movieRepository.GetByIdAsync(movieId);
            #region MyRegion
            //foreach(var cart in carts)
            // {
            //     if(cart.MovieId == movieId)
            //         return View("DeleteError");
            // }

            // if(movies== null)
            //     return RedirectToAction("NotFound"); 
            #endregion
            if (isMovieInCart)
            {
                //return PartialView("_DeleteErrorPertialView");
                return Json(new { isInCart = true });
            }
            await _movieRepository.DeleteAsync(movieId);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Create()
        {
            var viewModel = new MovieViewModel();
            var cinemas = _dbContext.Cinemas.ToList();
            var producers = _dbContext.producers.ToList();
            viewModel.Cinemas = cinemas.Select(c => new CinemaViewModel { Id = c.ID, Name = c.Name }).ToList();
            viewModel.Producers = producers.Select(c => new ProducerViewModel { Id = c.ID, Name = c.FullName }).ToList();

            return View(viewModel);
        }
        [HttpPost]
        public async Task<ActionResult> Create([Bind("Name", "Description", "StartDate", "EndDate","ImageFile","Price","MovieCategory", "SelectedCinemaId", "SelectedProducerId")] MovieViewModel movieViewModel)
        {
            if (!ModelState.IsValid)
             {

                return View();
            }
            string wwwRootPath = _webHostEnvironment.WebRootPath;
            string fileName = Path.GetFileNameWithoutExtension(movieViewModel.ImageFile.FileName);
            string extension = Path.GetExtension(movieViewModel.ImageFile.FileName);
            movieViewModel.ImagePath = fileName = fileName + DateTime.Now.ToString("yymmssff") + extension;
            string path = Path.Combine(wwwRootPath + "/Images/", fileName);
            using (var fileStream = new FileStream(path, FileMode.Create))
            {
                await movieViewModel.ImageFile.CopyToAsync(fileStream);
            }
            var movie = new Movie
            {
                Id = movieViewModel.Id,
                Name = movieViewModel.Name,
                StartDate = movieViewModel.StartDate,
                EndDate = movieViewModel.EndDate,
                ImageFile = movieViewModel.ImageFile,
                ImagePath = movieViewModel.ImagePath,
                Price = movieViewModel.Price,
                MovieCategory = movieViewModel.MovieCategory,
                CinemaId = movieViewModel.SelectedCinemaId, 
                ProducerId = movieViewModel.SelectedProducerId,
                Description = movieViewModel.Description,   
            };

            await _movieRepository.AddAsync(movie);


            return RedirectToAction("Index");
        }
    }
}

CinemaBooking/Controllers/ProducerController.cs
using CinemaBooking.Repositories.ProducerRepository;
using Microsoft.AspNetCore.Authorization;

namespace CinemaBooking.Controllers
{
    public class ProducerController : Controller
    {

        private readonly IProducerRepository _producerrepository;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ProducerController(IProducerRepository producerrepository, IWebHostEnvironment  webHostEnvironment)
        {
            _producerrepository = producerrepository;
            _webHostEnvironment = webHostEnvironment;
        }

        [Authorize]
        public async Task<IActionResult> Index(string stringSearch)
        {
            IEnumerable<Producer>? producers = await _producerrepository.GetAllAsync();
            ViewData["CurrentFilter"] = stringSearch;
            if (!string.IsNullOrEmpty(stringSearch))
            {
                producers = producers.Where(m => m.FullName.IndexOf(stringSearch, StringComparison.OrdinalIgnoreCase) >= 0).ToList();
            }
            return View(producers);
        }
        [Authorize]

        public async Task<IActionResult> Create()
        {
            return View();
        }
       
        [HttpPost]
        public async Task<IActionResult> Create([Bind("FullName","Bio","ImageFile")]Producer producer)
         {
            if (!ModelState.IsValid)
            {
                return View(producer);
            }
            string wwwRootPath = _webHostEnvironment.WebRootPath;
            string fileName = Path.GetFileNameWithoutExtension(producer.ImageFile.FileName);
            string extension = Path.GetExtension(producer.ImageFile.FileName);
            producer.ImagePath = fileName = fileName + DateTime.Now.ToString("yymmssff") + extension;
            string path = Path.Combine(wwwRootPath + "/Images/", fileName);
            using (var fileStream = new FileStream(path, FileMode.Create))
            {
                await producer.ImageFile.CopyToAsync(fileStream);
            }


            await _producerrepository.AddAsync(producer);


            return RedirectToAction("Index");

        }

        [Authorize]

        public async Task<IActionResult> Detail(int id)
        {
            var result = await _producerrepository.GetByIdAsync(id);
            if (result == null) return View("Empty");
            return View(result);
        }

        [Authorize]
        public async Task<IActionResult> Edit(int id)
        {
            var result = await _producerrepository.GetByIdAsync(id);
            if (result == null) return View("Empty");
            return View(result);
        }
     
        [HttpPost]
        public async Task<IActionResult> Edit(int id,[Bind("ID","FullName", "Bio", "ImagePath")] Producer producer)
        {
            if (!ModelState.IsValid)
            {
                return View(producer);
            }
            

            await _producerrepository.EditAsync(id,producer);


            return RedirectToAction("Index");

        }
        [Authorize]

        public async Task<IActionResult> Delete(int id)
        {
            var result = await _producerrepository.GetByIdAsync(id);
            if (result == null) return View("NotFound");
            return View(result);
        }
   
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmation(int id)
        {
            var result = await _producerrepository.GetByIdAsync(id);
            if (result == null) return View("NotFound");



            await _producerrepository.DeleteAsync(id);


            return RedirectToAction(nameof(Index));

        }
    }
}

CinemaBooking/Views/Shared/NotFound.cshtml
<div class="container p-5 text-center">
    <img src="https://i.pinimg.com/564x/68/98/7f/68987ffc834dc2c2e3723279c2c8588c.jpg" alt="Page Not Found" class="img-fluid not-found-image">
    <h1 class="not-found-title">404 - Page Not Found</h1>
    <p class="not-found-message">The requested page could not be found.</p>
    <p class="not-found-message">Please check the URL or navigate back to the home page.</p>
    <i class="bi bi-emoji-frown not-found-icon"></i>
  </div>

CinemaBooking/Views/Shared/_CartItemCount.cshtml
@*@{
    var cartId = GetCurrentCartId();
}*@
@{
    //var itemCount = await Html.Action("GetCartItemCount", "CartItem");
}

@if (!User.IsInRole("Admin"))
{
    <a id="cartLink" class="m-1 position-relative" asp-controller="CartItem" asp-action="Index">
        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
            <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
        </svg>
        @if (User.Identity.IsAuthenticated)
        {
            <span id="cartItemCount" class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                0<span class="visually-hidden">items in cart</span>
            </span>
        }
    </a>


}
<script>
    function updateCartItemCount() {
        $.ajax({
            url: '@Url.Action("GetCartItemCount", "CartItem")',
            type: 'GET',
            success: function (data) {
                $('#cartItemCount').text(data);
            },
            error: function (error) {
                console.log(error);
            }
        });
    }

    // Call the function once on page load
    $(document).ready(function () {
        updateCartItemCount();
    });
</script>

CinemaBooking/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity﻿
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CinemaBooking</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CinemaBooking.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
                <a class="navbar-brand text-dark" asp-controller="Movie" asp-action="index">Cinema Booking</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link text-dark" aria-current="page" asp-controller="Movie" asp-action="index">
                                Movies
                            </a>
                        </li>
                        @if (User.Identity.IsAuthenticated && User.IsInRole("User"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" aria-current="page" asp-controller="CartItemHistory" asp-action="index">
                                    Orders History
                                </a>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark"  asp-controller="Movie" asp-action="create">
                                    Add Movie
                                </a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Mangements
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item text-dark" asp-controller="Actor" asp-action="index"><i class="bi bi-film"></i>Actors</a></li>
                                    <li><a class="dropdown-item text-dark" asp-controller="Producer" asp-action="index">Producers</a></li>
                                    <li><a class="dropdown-item text-dark" asp-controller="Cinema" asp-action="index">Cinemas</a></li>
                                    <li><a class="dropdown-item text-dark" asp-controller="Security" asp-action="index">Security</a></li>
                                    <li><a class="dropdown-item text-dark" asp-controller="Security" asp-action="GetAllUsers">Users</a></li>

                                </ul>
                            </li>

                        }
                    </ul>
                    <form method="get" asp-controller="Movie" asp-action="index" class="d-flex" role="search">
                        <input class="form-group  me-2" name="stringSearch" type="search" placeholder="Search" aria-label="Search">

                        @* <a class="form-group class="mt-1" asp-controller="Movie" asp-action="index">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
                        </svg>
                        </a>*@
                    </form>
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <a class=" navbar-brand text-dark" aria-current="page" asp-controller="Account" asp-action="login">
                            Login
                        </a>
                    }
                    @*  @Html.Partial("_CartItemCount")*@

                    <div>
                        @await Component.InvokeAsync("CartIcon")
                    </div>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <form class="nav-link" asp-controller="Account" asp-action="logout">
                            <input type="submit" value="Logout" />
                        </form>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CinemaBooking
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>