CinemaBooking/Models/Movie.cs
using CinemaBooking.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CinemaBooking.Models
{
    public class Movie
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Name of the Movie is Required")]
        
        public string Name { get; set; }

        [Required(ErrorMessage = "Please select file.")]
        [RegularExpression(@"([a-zA-Z0-9\s_\\.\-:])+(.png|.jpg|.jpeg)$", ErrorMessage = "Only Image files allowed and should be 5MB or lower.")]
        public string ImagePath { get; set; }

        [Required(ErrorMessage = "Description is Required")]
        [StringLength(100, MinimumLength = 10)]
        public string Description { get; set; }

        [Required(ErrorMessage = "StartDate is Required")]
        [DisplayFormat(DataFormatString = "{0:dd MMM yy}", ApplyFormatInEditMode = true)]
        public DateTime StartDate { get; set; }

        [Required(ErrorMessage = "EndDate is Required")]
        [DisplayFormat(DataFormatString = "{0:dd MMM yy}", ApplyFormatInEditMode = true)]

        public DateTime EndDate { get; set; }

        [Required(ErrorMessage = "Price is Required")]

        public decimal Price { get; set; }
        [Required]
        public MovieCategory MovieCategory { get; set; }

        [ForeignKey("Cinema")]
        public int CinemaId { get; set; }
        public Cinema Cinema { get; set; }

        [ForeignKey("Producer")]
        public int ProducerId { get; set; }
        public Producer Producer { get; set; }

      

        public List<Actor_Movie> Actor_Movies { get; set; } = new List<Actor_Movie>();

        public List<CartItem> CartItems { get; set; } = new List<CartItem>();


    }
}

CinemaBooking/Controllers/CartItemController.cs
using CinemaBooking.Repositories.CartItemHistoryRepository;

namespace CinemaBooking.Controllers
{
    public class CartItemController : Controller
    {
        protected readonly ICartItemRepository _cartItemRepository;
        protected readonly IMovieRepository _movieRepository;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ICartRepository _cartRepository;
        private readonly ICartItemHistoryRepository _cartItemHistory;
        public CartItemController(ICartItemRepository cartItemRepository, IMovieRepository movieRepository, UserManager<ApplicationUser> userManager, ICartRepository cartRepository, ICartItemHistoryRepository cartItemHistory)
        {
            _cartItemRepository = cartItemRepository;
            _movieRepository = movieRepository;
            _userManager = userManager;
            _cartRepository = cartRepository;
            _cartItemHistory = cartItemHistory;
        }
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {

                return RedirectToAction("Login", "Account");
            }

            var cart = await _cartRepository.GetByUserIdAsync(user.Id);
            if (cart == null || cart.CartItems == null || cart.CartItems.Count == 0)
            {

                return View("CartIsEmpty");
            }

            return View(cart.CartItems);
        }
        public async Task<IActionResult> AddItem() => View();

        #region AddItemv1
        //[HttpPost]
        //public async Task<ActionResult> AddItem(int movieId)
        //{
        //    var movie = await _movieRepository.GetByIdAsync(movieId);
        //    var cartitems = new CartItem
        //    {
        //        MovieId = movie.Id,
        //        MovieName = movie.Name,
        //        Price = movie.Price,
        //        Amount = 1,


        //    };
        //    cartitems.Total = _cartItemRepository.CalculateTotal(cartitems.Amount, cartitems.Price);

        //    await _cartItemRepository.AddAsync(cartitems);
        //    return RedirectToAction("Index");
        //} 
        #endregion
        private async Task<Cart> GetOrCreateCart(string userId)
        {
            var cart = await _cartRepository.GetByUserIdAsync(userId);
            if (cart == null)
            {
                cart = new Cart
                {
                    UserId = userId,
                    CartDate = DateTime.Now,
                    CartItems = new List<CartItem>(),

                };

                await _cartRepository.AddAsync(cart);
            }
            return cart;
        }
        [HttpPost]
        public async Task<ActionResult> AddItem(int movieId)
        {
            var movie = await _movieRepository.GetByIdAsync(movieId);
            var user = await _userManager.GetUserAsync(User);

            if (user == null || !await _userManager.IsInRoleAsync(user, "User"))
            {

                return RedirectToAction("Login", "Account");
            }
            else if (await IsMovieExistInCart(user.Id, movie.Name))
            {
                TempData["AlertMessage"] = "The Movie Is Already Exist In The Cart....";
                return RedirectToAction("Index","Movie");
            }
            else
            {
                var cart = await GetOrCreateCart(user.Id);
                var cartItem = new CartItem
                {
                    MovieId = movie.Id,
                    MovieName = movie.Name,
                    Price = movie.Price,
                    Amount = 1,
                    Total = _cartItemRepository.CalculateTotal(1, movie.Price),
                    CartId = cart.ID,

                };

                await _cartItemRepository.AddAsync(cartItem);
                return RedirectToAction("Index");

            }
        }
        [HttpPost]
        public async Task<IActionResult> RemoveFromCart(int cartItemId)
        {
            await _cartItemRepository.DeleteAsync(cartItemId);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<ActionResult> UpdateQuantity(int itemId, int amount)
        {
            var cartItem = await _cartItemRepository.GetByIdAsync(itemId);
            if (cartItem != null)
            {
                cartItem.Amount = amount;
                cartItem.Total = _cartItemRepository.CalculateTotal(amount, cartItem.Price);
                await _cartItemRepository.EditAsync(itemId, cartItem);
            }

            return RedirectToAction("Index");
        }

        #region Checkoutv1
        //[Authorize]
        //[HttpPost]
        //public IActionResult Checkout()
        //{
        //    if (User.Identity.IsAuthenticated &&User.IsInRole("User"))
        //    {

        //        return View("Sucess");

        //    }
        //    else
        //    {
        //        return RedirectToAction("Login","Account");

        //    }
        //} 
        #endregion
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Checkout()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {

                return RedirectToAction("Login", "Account");
            }

            var cart = await _cartRepository.GetByUserIdAsync(user.Id);
            if (cart == null || cart.CartItems.Count == 0)
            {

                return RedirectToAction("CartIsEmpty");
            }

            await MoveCartItemsToHistory(cart);
            // await _cartRepository.EditAsync(cart.ID, cart);

            return View("Sucess");
        }
        private async Task MoveCartItemsToHistory(Cart cart)
        {
            var cartItems = cart.CartItems.Select(item => new CartItemsHistory
            {
                UserId = cart.UserId,
                MovieId = item.MovieId,
                MovieName = item.MovieName,
                Price = item.Price,
                Amount = item.Amount,
                Total = item.Total,
                CheckoutDate = DateTime.Now,
                CartId = cart.ID,


            }).ToList();


            await _cartItemHistory.AddAllAsync(cartItems);
            await _cartItemRepository.DeleteAllAsync(cart.CartItems);
        }
        #region CartCount

        //public ActionResult GetCount(int cartId)
        //{
        //    var cart = _cartRepository.GetByIdAsync(cartId);
        //    int cartItemCount = GetCartItemCount(cart.Id);
        //    ViewBag.CartItemCount = cartItemCount;
        //    return View();
        //}

        //public IActionResult GetCartCount(int cartId)
        //{
        //    var cart = _cartRepository.GetByIdAsync(cartId);
        //    int cartItemCount = GetCartItemCount(cart.Id);
        //    return Json(new { Count = cartItemCount });
        //}
        //private int GetCartItemCount(int cartId)
        //{
        //    return _cartRepository.CountCart(cartId);
        //}


        //public async Task<int> GetCartItemCount()
        //{
        //    var user = await _userManager.GetUserAsync(User);
        //    if (user == null)
        //    {
        //        return 0;
        //    }

        //    var cart = await _cartRepository.GetByUserIdAsync(user.Id);
        //    if (cart == null || cart.CartItems == null)
        //    {
        //        return 0;
        //    }

        //    return cart.CartItems.Count;
        //} 
        #endregion

        public async Task<bool> IsMovieExistInCart(string userId,string movieName)
        {
            var user = await _userManager.FindByIdAsync(userId);
            if (user == null) return false;

            var cart = await _cartRepository.GetByUserIdAsync(user.Id);
            if (cart == null) return false;

            return  cart.CartItems.Any(CartItem => CartItem.MovieName.Equals(movieName, StringComparison.OrdinalIgnoreCase));

        }


    }
}

CinemaBooking/Controllers/MovieController.cs
using CinemaBooking.Data.ViewModels;

namespace CinemaBooking.Controllers
{
    public class MovieController : Controller
    {
        private readonly IMovieRepository _movieRepository;
        private readonly ICartItemRepository _cartItemRepository;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly ApplicationDbContext _dbContext;
        public MovieController(IMovieRepository movieRepository, ICartItemRepository cartItemRepository, IWebHostEnvironment webHostEnvironment, ApplicationDbContext dbContext)
        {
            _movieRepository = movieRepository;
            _cartItemRepository = cartItemRepository;
            _webHostEnvironment = webHostEnvironment;
            _dbContext = dbContext;
        }
        public async Task<IActionResult> Index(string stringSearch)
        {
            IEnumerable<Movie>? movies = await _movieRepository.GetAllAsync();
            ViewData["CurrentFilter"] = stringSearch;
            if (!string.IsNullOrEmpty(stringSearch))
            {
                movies = movies.Where(m => m.Name.IndexOf(stringSearch, StringComparison.OrdinalIgnoreCase) >= 0).ToList();
            }
            return View(movies);

        }

        public async Task<IActionResult> Details(int id)
        {
            var movie = await _movieRepository.GetByIdAsync(id);
            return View(movie);
        }
        [HttpPost]
        public async Task<ActionResult> Delete(int movieId)
        {
            var isMovieInCart = await _cartItemRepository.IsMovieInCart(movieId);
            var movies = await _movieRepository.GetByIdAsync(movieId);
            #region MyRegion
            //foreach(var cart in carts)
            // {
            //     if(cart.MovieId == movieId)
            //         return View("DeleteError");
            // }

            // if(movies== null)
            //     return RedirectToAction("NotFound"); 
            #endregion
            if (isMovieInCart)
            {
                //return PartialView("_DeleteErrorPertialView");
                return Json(new { isInCart = true });
            }
            await _movieRepository.DeleteAsync(movieId);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Create()
        {
            var viewModel = new MovieViewModel();
            var cinemas = _dbContext.Cinemas.ToList();
            var producers = _dbContext.producers.ToList();
            viewModel.Cinemas = cinemas.Select(c => new CinemaViewModel { Id = c.ID, Name = c.Name }).ToList();
            viewModel.Producers = producers.Select(c => new ProducerViewModel { Id = c.ID, Name = c.FullName }).ToList();

            return View(viewModel);
        }
        [HttpPost]
        public async Task<ActionResult> Create([Bind("Name", "Description", "StartDate", "EndDate","ImageFile","Price","MovieCategory", "SelectedCinemaId", "SelectedProducerId")] MovieViewModel movieViewModel)
        {
            if (!ModelState.IsValid)
             {

                return View();
            }
            string wwwRootPath = _webHostEnvironment.WebRootPath;
            string fileName = Path.GetFileNameWithoutExtension(movieViewModel.ImageFile.FileName);
            string extension = Path.GetExtension(movieViewModel.ImageFile.FileName);
            movieViewModel.ImagePath = fileName = fileName + DateTime.Now.ToString("yymmssff") + extension;
            string path = Path.Combine(wwwRootPath + "/Images/", fileName);
            using (var fileStream = new FileStream(path, FileMode.Create))
            {
                await movieViewModel.ImageFile.CopyToAsync(fileStream);
            }
            var movie = new Movie
            {
                Id = movieViewModel.Id,
                Name = movieViewModel.Name,
                StartDate = movieViewModel.StartDate,
                EndDate = movieViewModel.EndDate,
                ImageFile = movieViewModel.ImageFile,
                ImagePath = movieViewModel.ImagePath,
                Price = movieViewModel.Price,
                MovieCategory = movieViewModel.MovieCategory,
                CinemaId = movieViewModel.SelectedCinemaId, 
                ProducerId = movieViewModel.SelectedProducerId,
                Description = movieViewModel.Description,   
            };

            await _movieRepository.AddAsync(movie);


            return RedirectToAction("Index");
        }
    }
}

CinemaBooking/Views/Movie/Create.cshtml
@model MovieViewModel
@using CinemaBooking.Data;
@using CinemaBooking.Enums
@using CinemaBooking.Data.ViewModels;

@{
    ViewData["Title"] = "Adding a new Movie";
}


<form asp-action="Create" class="row g-3" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger">
    </div>
    <div class="form-group col-md-12">
        <label asp-for="Name" for="validationCustom01" class="form-label fw-bold">Name :</label>
        <input asp-for="Name" type="text" class="form-control" id="validationCustom01" value="">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group col-md-12">
        <label asp-for="Description" for="validationCustom02" class="control-label fw-bold">Description :</label>
        <input asp-for="Description" type="text" class="form-control" id="validationCustom02" value="">
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group col-md-12">
        <label asp-for="Price" for="validationCustom02" class="control-label fw-bold">Price :</label>
        <input asp-for="Price" type="number" class="form-control" id="validationCustom02" value="">
        <span asp-validation-for="Price" class="text-danger"></span>
    </div>

    <div class="form-group col-md-12">
        <label asp-for="StartDate" for="validationCustom02" class="control-label fw-bold">StartDate :</label>
        <input asp-for="StartDate" type="date" class="form-control" id="validationCustom02" value="">
        <span asp-validation-for="StartDate" class="text-danger"></span>
    </div>
    <div class="form-group col-md-12">
        <label asp-for="EndDate" for="validationCustom02" class="control-label fw-bold">EndDate :</label>
        <input asp-for="EndDate" type="date" class="form-control" id="validationCustom02" value="">
        <span asp-validation-for="EndDate" class="text-danger"></span>
    </div>

    <label for="validationCustom02" class="control-label fw-bold">MovieCategoy :</label>
    @Html.DropDownList("Categories",Html.GetEnumSelectList<MovieCategory>(),"Select Category",new {@class = "form-control"})


    <div class="form-group">
        <label asp-for="SelectedCinemaId" class="control-label fw-bold">Select Cinema:</label>
        @Html.DropDownListFor(m => m.SelectedCinemaId, new SelectList(Model.Cinemas, "Id", "Name"),"Select Cinema", new { @class = "form-control" })
        <span asp-validation-for="SelectedCinemaId" class="text-danger"></span>
    </div>
    
    <div class="form-group">
        <label asp-for="SelectedProducerId" class="control-label fw-bold">Select Producer:</label>
        @Html.DropDownListFor(m => m.SelectedProducerId, new SelectList(Model.Producers, "Id", "Name"),"Select Producer", new { @class = "form-control" })
        <span asp-validation-for="SelectedProducerId" class="text-danger"></span>
    </div>

    <div class="form-group col-md-12">
        <label asp-for="ImageFile" for="validationCustom02" class="control-label fw-bold">Movie Image</label>
        <input asp-for="ImageFile" accept="image/*">
        <span asp-validation-for="ImageFile" class="text-danger"></span>
    </div>


    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <div>
        <img id="output" width="200" />
    </div>

    <div class="form-group d-flex justify-content-center">
        <input type="submit" value="Create" class="btn btn-outline-success" />

    </div>
</form>
<script>
    function handleFileUpload(event) {
        var file = event.target.files[0];
        var reader = new FileReader();

        reader.onload = function(e) {
            $('#output').attr('src', e.target.result);
            $('#output').show();
        }

        reader.readAsDataURL(file);
    }

    $('#file').on('change', handleFileUpload);
</script>

CinemaBooking/Views/Movie/Details.cshtml
@model Movie

@{
    ViewData["Title"] = "Movie Detail";
}

<div class="container">

    <div class="text-center  mt-2" style="padding:20px;background-color:#9a8c98">
        <h3 class="text-capitalize">@Model.Description</h3>
    </div>

    <div class="form-group col-md-12">
        <label asp-for="Name" for="formFile" class="control-label">Movie Name:</label>
        <input asp-for="Name" class="form-control" readonly>
    </div>

    <div class="form-group col-md-12">
        <label asp-for="StartDate" for="validationCustom01" class="form-label">Start Date:</label>
        <input asp-for="StartDate" type="text" class="form-control" id="validationCustom01" readonly>
    </div>

    <div class="form-group col-md-12">
        <label asp-for="EndDate" for="validationCustom02" class="form-label">End Date:</label>
        <input asp-for="EndDate" type="text" class="form-control" id="validationCustom02" readonly>
    </div>

    <div class="form-group col-md-12">
        <label asp-for="Price" for="validationCustom02" class="form-label">Price:</label>
        <input asp-for="Price" type="text" class="form-control" id="validationCustom02" readonly>
    </div>

    <div class="form-group col-md-12">
        <label asp-for="MovieCategory" for="validationCustom02" class="form-label">Movie Category:</label>
        <input asp-for="MovieCategory" type="text" class="form-control" id="validationCustom02" readonly>
    </div>

    <div class="form-group col-md-12">
        <label asp-for="Cinema.Name" for="validationCustom02" class="form-label">Cinema Name:</label>
        <input asp-for="Cinema.Name" type="text" class="form-control" id="validationCustom02" readonly>
    </div>
    <div class="d-flex justify-content-center mt-2">
        <form method="post" asp-controller="CartItem" asp-action="AddItem">

            <button style="background-color:#9a8c98" class="btn">Add To Cart</button>
        </form>

    </div>

CinemaBooking/Views/Movie/Index.cshtml
@model IEnumerable<Movie>

@{
    ViewData["Title"] = "List of Movies";
}
@if(TempData["AlertMessage"] != null)
{
    
<div class="alert alert-danger mt-3" role="alert">
 @TempData["AlertMessage"]
</div>
}

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4 col-xs-6 border-primary mb-3">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white" style="background-color:#9a8c98">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @item.Name
                                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                                    {
                                        <a class="text-white float-right" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i></a>
                                    }
                                </h5>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src=@Url.Content("~/Images/"+@item.ImagePath) width="100%" alt="@item.Name">
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <p class="card-text">@item.Description</p>
                            <p class="card-text"><b>Cinema: </b>@item.Cinema.Name</p>
                            <p class="card-text"><b>Category: </b>@item.MovieCategory</p>
                            <p class="card-text"><b>Start Date: </b>@item.StartDate.ToString("dd MMM yy")</p>
                            <p class="card-text"><b>End Date: </b>@item.EndDate.ToString("dd MMM yy")</p>
                            <p class="card-text ">
                                <b>Status: </b>
                                @if (DateTime.Now >= item.StartDate && DateTime.Now <= item.EndDate)
                                {
                                    <span class="badge bg-success text-white">AVAILABLE</span>
                                }
                                else if (DateTime.Now > item.EndDate)
                                {
                                    <span class="badge bg-danger text-white">EXPIRED</span>
                                }
                                else
                                {
                                    <span class="badge bg-primary text-white">UPCOMING</span>
                                }
                            </p>

                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer ">
                            <p class="card-text">
                                @if (!User.IsInRole("Admin"))
                                {
                                    <form method="post" asp-controller="CartItem" asp-action="AddItem" class="d-inline">
                                        <input type="hidden" name="movieId" value="@item.Id" />
                                        <button type="submit" class="btn text-white @((DateTime.Now > item.EndDate) ? "disabled" : "")"
                                        style="background-color: #A076F9">
                                            <i class="bi bi-cart-plus"></i> Add to Cart (Price @item.Price.ToString("c"))
                                        </button>
                                    </form>

                                }
                                <div class="d-flex justify-content-between mt-2">
                                    <a class="btn  float-right" asp-action="Details" asp-route-id="@item.Id" style="color: #A076F9">
                                        Show Details
                                    </a>

                                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                                    {
                                        <form method="post" asp-action="Delete" id="popupContainer" class="d-inline">
                                            <input type="hidden" name="movieId" value="@item.Id" />
                                            @*<button type="submit" class="btn btn-danger">Remove</button>*@
                                            <button class="delete-movie" data-movie-id="@item.Id" data-bs-toggle="modal" data-bs-target="#popup">Delete</button>
                                            @await Html.PartialAsync("_DeleteErrorPopup")
                                        </form>
                                    }

                                </div>

                            </p>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function() {
        $(".delete-movie").click(function(event) {
            event.preventDefault();

            var deleteButton = $(this);
            var movieId = deleteButton.data("movie-id");
            $("#popup").hide();

            deleteButton.prop("disabled", true);

            $.ajax({
                url: "/Movie/Delete",
                type: "POST",
                data: { movieId: movieId },
                success: function(response) {
                    if (response.isInCart) {
                        $("#popup").show();
                    } else {

                        window.location.href = "/Movie";
                    }
                },
                error: function(xhr, status, error) {
                    console.error(error);
                },
                complete: function() {

                    deleteButton.prop("disabled", false);
                }
            });
        });

        $("#close-popup").click(function() {

            $("#popup").hide();
        });
    });

    $.ajax({
        url: '@Url.Action("AddItem", "CartItem")',
        type: 'POST',
        data: { movieId: movieId },
        success: function (result) {
            $('.badge').text(result.cartItemCount);
        }
    });
</script>

CinemaBooking/Views/Movie/_DeleteErrorPopup.cshtml
@*<style>
  #popup {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-color: rgba(0, 0, 0, 0.5);
    display: flex;
    align-items: center;
    justify-content: center;
  }

  #popup-content {
    background-color: #fff;
    padding: 20px;
    border-radius: 5px;
  }
</style>*@


@*<div id="popup" style="display: none;">
  <div id="popup-content">
    <p>You cannot delete this movie as it is in the cart.</p>
    <button id="close-popup">Close</button>
  </div>
</div>*@

<div id="popup" class="modal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div  class="modal-header" >
        <h5 class="modal-title text-uppercase" style="color:red">Warning!!</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p class="fw-bold">Some One Aleady Booking This Movie You CAN'T Delete It Now</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
      
      </div>
    </div>
  </div>
</div>